Lightcord/Lightcord

README.md

I wrote a small helper script that allows the user to both uninstall and install/update Lightcord.

Helper script added to readme.md

---

Lightcord_installer.sh
README.md

I added an update function to the original installer forked from [here](https://raw.githubusercontent.com/GermanBread/UsefulTools/main/Lightcord_dev_installer.sh) and merged it with the official repo so that it can be updated quicker when a new update is released.

Update installer script and merge with repo.

---

Lightcord_installer.sh
README.md

Because GermanBread made the original script, he/she deserves to be credited.

Add GermanBread github to script

---

Lightcord_installer.sh

1 - The "unzip" command had typos, resulting in no unzipping
2 - The "Lightcord.desktop" file gets moved TWICE
3 - The update function was completely borked, so I fixed it
4 - The 4th option was uneccesary, so I removed it

Important fixes to borked installer script

---

README.md

The script was not executed as root. I fixed it.

Added missing `sudo`

---

Lightcord_installer.sh

Add logo to linux install script 

---

README.md

Added my aur package which compiles the code at install time and added a one-liner AUR install sciprt

Edit AUR instructions

---

Lightcord_installer.sh

Fixes:
- no more downloading the .desktop file twice
Additions:
- troubleshooting menu

fixes and additions to install script

---

Lightcord_installer.sh

Option 4.1:
- troubleshooting can now "fix" .desktop files
Option 4.2:
- redirects the user to the discord server
Option 2:
- leftover .desktop files in [every home directory available]/.local/share/applications get deleted
Option 1:
- deletes "junk" files (files that are downloaded by the script) before downloading said files to prevent duplicates
Other:
- the Lightcord ASCII-art is orange now

Various inprovements to install script

---

Lightcord_installer.sh

Instead of using the desktop file in the official repo, which does not have the correct name for the binary, use echo to create a proper one. Then the troubleshooting option can be removed

Fix Desktop file

---

Lightcord_installer.sh

prevents clogging of the hard drive

add an option to delete the script after use

---

README.md

the name of the installer file is wrong

broke command 

---

README.md

- Slightly improved formatting
- Inform the user that running something as root isn't always a good idea

Clarify the install instructions

---

scripts/build.js

https://github.com/Lightcord/Lightcord/issues/130

Fixes #130

---

LULI.sh

Fixed incorrect variable name
Clarified instructions

Tweak NixOS error message

---

LULI.sh

I'd never forget to do stuff like this.

Remove "remove this script" promp

---

LULI.sh

I have no idea how that line at the end changed.

Change stuff in installer (good)

---

BetterDiscordApp/src/ui/addoncard.jsx

Fixed typo

---

BetterDiscordApp/src/modules/devMode.js

Fix Copy selector button being appended under reaction buttons

---

BetterDiscordApp/src/modules/core.js

Ignore my Github Desktop had a stroke and decided to commit to my fork

Update Lightcord Dev Badge id's
